### PR TITLE
Refactor to align with template-formula; fix failures

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes, 

but the existing formula is not working anyway

### Related issues and/or pull requests

The formula was failing because the hardcoded 2018 release is no longer available - see 
#28.  This PR fixes that issue and is a rewrite to align to template-formula. Travis is passing for various Linux.

### Describe the changes you're proposing

Refactored formula

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin Finally, review this one and pushed two commits on top to standardise the structure.  Please have a look at both and go ahead and merge if you're OK with the proposed changes.

* Checked with https://github.com/myii/ssf-formula/pull/177.

**Review by noelmcloughlin — COMMENTED** [review]
Thanks @myii for reviewing

**Comment by myii** [comment]
@noelmcloughlin There's another `yamllint` error introduced in your last commit and are you sure you mean to use `None` rather than `null` or even `~`?

* https://yaml.org/type/null.html

**Comment by myii** [comment]
https://travis-ci.com/github/saltstack-formulas/eclipse-formula/jobs/328737888#L303-L305

```bash
$ yamllint -s .
./pillar.example
  25:18     warning  too few spaces before comment  (comments)
```

**Comment by myii** [comment]
Forcing the `release`, so that we make ourselves official here...

**Pull request merged**
